# Generated by Django 3.1.7 on 2021-04-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210424_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('3', 'difficult'), ('1', 'easy')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('电子信息学院', '电子信息学院'), ('计算机科学与技术学院', '计算机科学与技术学院'), ('外国语学院', '外国语学院'), ('船舶与海洋工程学院', '船舶与海洋工程学院'), ('理学院', '理学院')], default=None, max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.CharField(choices=[('电子信息学院', '电子信息学院'), ('计算机科学与技术学院', '计算机科学与技术学院'), ('外国语学院', '外国语学院'), ('船舶与海洋工程学院', '船舶与海洋工程学院'), ('理学院', '理学院')], default=None, max_length=20, verbose_name='学院'),
        ),
    ]
