# Generated by Django 2.1 on 2021-05-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210516_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', '中等'), ('1', '简单'), ('3', '较难')], max_length=10, verbose_name='等级'),
        ),
    ]
