# Generated by Django 2.1 on 2021-05-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210523_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', '简单'), ('2', '中等'), ('3', '较难')], max_length=10, verbose_name='等级'),
        ),
    ]
